title: Hello, world! I'm David Freeman
# from main Jekyll YAML
# email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: tkdphoenix #if your site has a twitter account, enter it here

# From Jekyll main install. Flexible Jekyll theme is using `site-twitter` param.
# twitter_username: jekyllrb
github_username:  tkdphoenix

# Author Settings
author: Joel Grissom # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a web developer focusing on PHP and front-end development. <br><br>"No one keeps up with technology; we just fall behind at a different pace." <br>- My college professor # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: tkdphoenix # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: joelgrissom # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
# Theme keyword is from Jekyll install
# theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
